### ISSUE TITLE
TornadoSpawners hakkında

### ISSUE THREAD

**Issue by portlek** [Keyubu/plugin-paketi#1]
İyi günler, paketlerinizde kullandığınız "KeyubuSpawners" namı diğer TornadoSpawners eklentisi ekibimizde ki Halil arkadaşın ücretli eklentisidir, bu eklentinin ismini değiştirip bu şekilde yayınlamak yasaktır. Lütfen bu mesajı gördüğünüzde beni portlek#5502 discord adresinden ekleyin, 1 hafta içersinde hukuki işlemleri başlatacağız bilginize.

**Comment by sametgirginer** [comment]
**TornadoSpawners** sahibi bize bu eklentiyi ismini değiştirerek iletti. Eklentinin asıl sahibi siz misiniz bilmiyorum ancak kendisine sorabilirsiniz. Hızlı yanıt için discord sunucumuza gelebilirsiniz.

https://discord.me/keyubu

**Comment by sametgirginer** [comment]
Konu discord üzerinden görüşülmüştür.
